### ISSUE TITLE
Extends to comments, files, dashboard

### ISSUE THREAD

**Issue by fregante** [travelist/github-shortcuts#1]
Hello, in Refined GitHub this feature was discussed a few times but was never implemented:

- Issues: https://github.com/sindresorhus/refined-github/issues/1270
- Dashboard: https://github.com/sindresorhus/refined-github/issues/614
- Files in diffs/PRs: https://github.com/sindresorhus/refined-github/issues/853

Since you started the work on it already, it would be great to have your extension take care of all of these

**Comment by travelist** [comment]
Hello, thank you for the list of suggestions, all of them looks very nice to me.
I will start to work on them for the next step of this extension :)

**Comment by travelist** [comment]
I've implemented these features presented in the issues. 
I gonna close this issue but please let me know if there are any further requests, I'm happy to deal with. Thanks.
