### ISSUE TITLE
Duplicate functionality

### ISSUE THREAD

**Issue by fregante** [travelist/github-shortcuts#2]
GitHub already has this functionality on issue/PR lists with <kbd>j</kbd>, <kbd>k</kbd> and <kbd>enter</kbd>

![demo2](https://user-images.githubusercontent.com/1402241/80870203-45659880-8ca5-11ea-843f-8bf783de4ba3.gif)

**Comment by travelist** [comment]
Thanks for the comment, I haven't noticed this Github feature!
Although there is official support, I will keep arrow key bindings as part of this extension unless it conflict with any other functionality.
